name: horse_point
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Authentication
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_analytics: ^7.1.1
  cloud_firestore: ^1.0.3
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^5.0.1

  provider: ^5.0.0
  http: ^0.13.1

  clippy_flutter: ^1.1.1
  form_field_validator: ^1.1.0
  toast: ^0.1.5
  flutter_spinkit: ^4.1.2
  overlay_container: ^0.0.5+1
  shared_preferences: ^2.0.5
  page_transition: ^1.1.6
  sticky_headers: ^0.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/login_background.jpg
    - assets/images/default_profile.png
    - assets/logos/facebook_logo.png
    - assets/logos/google_logo.png
    - lang/
  
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoSans-SemiBold.ttf