name: horse_point
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Authentication
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^5.0.1

  provider: ^5.0.0
  http: ^0.13.1

  clippy_flutter: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/login_background.jpg